import { Stack, chakra } from '@chakra-ui/react'
import { observer } from 'mobx-react'
import Head from 'next/head'
import Icon from 'components/Icon'

const Page404 = () => {
  return (
    <>
      <Head>
        <title>ONO | 404</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/icons/logo.svg" />
      </Head>
      <chakra.main>
        <Stack backgroundColor="#202A3B" justifyContent={'center'} alignItems={'center'} h="100vh">
          <Icon iconName="logo.svg" width={402} height={55} className="ono-logo" alt="ono-logo" />
        </Stack>
      </chakra.main>
    </>
  )
}

export default observer(Page404)
