import Head from 'next/head'
import BasicModal from 'components/BasicModal'
import {
  Button,
  useDisclosure,
  Text,
  VStack,
  Textarea,
  FormControl,
  FormLabel,
  Input,
  Image,
  Radio,
  RadioGroup,
  Stack
} from '@chakra-ui/react'
import { useState } from 'react'

const Home = () => {
  const [previewImage, setPreviewImage] = useState('')
  const { isOpen: isConfirmModalOpen, onOpen: onOpenConfirmModal, onClose: onCloseConfirmModal } = useDisclosure()
  const { isOpen: isAnnouncementOpen, onOpen: onOpenAnnouncement, onClose: onCloseAnnouncement } = useDisclosure()
  const { isOpen: isFeedbackModalOpen, onOpen: onOpenFeedbackModal, onClose: onCloseFeedbackModal } = useDisclosure()
  const {
    isOpen: isServiceRequestModalOpen,
    onOpen: onOpenServiceRequestModal,
    onClose: onCloseServiceRequestModal
  } = useDisclosure()
  const { isOpen: isContactMeModalOpen, onOpen: onOpenContactMeModal, onClose: onCloseContactMeModal } = useDisclosure()
  const {
    isOpen: isResidentRegistrationModalOpen,
    onOpen: onOpenResidentRegistrationModal,
    onClose: onCloseResidentRegistrationModal
  } = useDisclosure()
  const { isOpen: isLightBoxModalOpen, onOpen: onOpenLightBoxModal, onClose: onCloseLightBoxModal } = useDisclosure()
  const { isOpen: isSurveyModalOpen, onOpen: onOpenSurveyModal, onClose: onCloseSurveyModal } = useDisclosure()

  const contactMeFormContent = (
    <FormControl>
      <FormLabel>Email Address</FormLabel>
      <Input type="email" placeholder="Enter your email" />
      <FormLabel mt={4}>Phone Number</FormLabel>
      <Input type="tel" placeholder="Enter your phone number" />
    </FormControl>
  )
  const feedbackFormContent = <Textarea placeholder="Please share your feedback or complaints here." />
  const serviceRequestFormContent = (
    <FormControl>
      <FormLabel>Service Type</FormLabel>
      <Input placeholder="Type of service requested" />
      <FormLabel marginTop={4}>Additional Details</FormLabel>
      <Textarea placeholder="Describe your request" />
    </FormControl>
  )
  const residentRegistrationFormContent = (
    <FormControl>
      <FormLabel>Full Name</FormLabel>
      <Input placeholder="Enter your full name" />
      <FormLabel mt={4}>Apartment Number</FormLabel>
      <Input placeholder="Enter your apartment number" />
      <FormLabel mt={4}>Email Address</FormLabel>
      <Input type="email" placeholder="Enter your email address" />
    </FormControl>
  )
  const lightBoxContent = <Image src={previewImage} alt="Preview" maxW="100% " maxH="80vh" objectFit="contain" />

  const images = ['https://picsum.photos/200/300', 'https://picsum.photos/450']
  return (
    <div>
      <Head>
        <title>Front end test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack spacing={4} padding={6} align="flex-start">
        <Text>Confirm Modal (default): Can use when cancel form, exit page, ...</Text>
        <BasicModal
          isOpen={isConfirmModalOpen}
          onClose={onCloseConfirmModal}
          cancelButtonText="Cancel"
          confirmButtonText="Confirm"
        />
        <Button onClick={onOpenConfirmModal}>Open Confirm Modal</Button>
        <Text>Announcements</Text>
        <BasicModal
          isOpen={isAnnouncementOpen}
          onClose={onCloseAnnouncement}
          titleText="Maintenance Schedule"
          bodyText="Please be informed about the upcoming maintenance schedule..."
          confirmButtonText="Got it!"
        />
        <Button onClick={onOpenAnnouncement}>Open Announcements Modal</Button>
        <Text>Resident Feedback</Text>
        <BasicModal
          isOpen={isFeedbackModalOpen}
          onClose={onCloseFeedbackModal}
          titleText="We Value Your Feedback"
          bodyContent={feedbackFormContent}
          confirmButtonText="Submit Feedback"
        />
        <Button onClick={onOpenFeedbackModal}>Open Feedback Modal</Button>
        <Text>Service Request Confirmation</Text>
        <BasicModal
          isOpen={isServiceRequestModalOpen}
          onClose={onCloseServiceRequestModal}
          titleText="Confirm Service Request"
          bodyContent={serviceRequestFormContent}
          confirmButtonText="Confirm Request"
          cancelButtonText="Cancel"
        />
        <Button onClick={onOpenServiceRequestModal}>Open Service Request Modal</Button>
        <Text>Contact Information Update</Text>
        <BasicModal
          isOpen={isContactMeModalOpen}
          onClose={onCloseContactMeModal}
          titleText="Update Your Contact Information"
          bodyContent={contactMeFormContent}
          confirmButtonText="Update"
        />
        <Button onClick={onOpenContactMeModal}>Open Contact Me Modal</Button>
        <Text>Resident Registration</Text>
        <BasicModal
          isOpen={isResidentRegistrationModalOpen}
          onClose={onCloseResidentRegistrationModal}
          titleText="Resident Registration"
          bodyContent={residentRegistrationFormContent}
          confirmButtonText="Register"
        />
        <Button onClick={onOpenResidentRegistrationModal}>Open Resident Registration Modal</Button>
        <VStack>
          <Text>Image Gallery with LightBox Modal</Text>
          {images.map((imageUrl, index) => (
            <img
              key={index}
              src={imageUrl}
              alt={`Preview ${index}`}
              onClick={() => {
                setPreviewImage(imageUrl)
                onOpenLightBoxModal()
              }}
              style={{ cursor: 'pointer', maxWidth: '150px', margin: '10px' }} // Style as needed
            />
          ))}
          <BasicModal
            isOpen={isLightBoxModalOpen}
            onClose={onCloseLightBoxModal}
            bodyContent={lightBoxContent}
            confirmButtonText="Close"
          />
        </VStack>
        <Text> Custom Survey/Poll Modal</Text>
        <BasicModal
          isOpen={isSurveyModalOpen}
          onClose={onCloseSurveyModal}
          titleText="Resident Satisfaction Survey"
          bodyContent={
            <RadioGroup defaultValue="1">
              <Stack direction="column">
                <Radio value="1">Very Satisfied</Radio>
                <Radio value="2">Satisfied</Radio>
                <Radio value="3">Neutral</Radio>
                <Radio value="4">Dissatisfied</Radio>
                <Radio value="5">Very Dissatisfied</Radio>
              </Stack>
            </RadioGroup>
          }
          confirmButtonText="Submit"
        />
        <Button onClick={onOpenSurveyModal}>Open Survey Modal</Button>
      </VStack>
    </div>
  )
}

export default Home
